att/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

app_name='att'

urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r"^register/",views.attendancereg,name='att'),
    url(r'^comitteelogin/',views.ulogin,name='auth_login'),
    url(r'^committeeview/',views.attviewauth,name='attviewauth'),
    url(r'^allleavelist/',views.attview,name='attview'),
    url(r'^approve/(?P<attsheet_id>[0-9]+)',views.approveit,name='approveit'),
    url(r'^reject/(?P<attsheet_id>[0-9]+)',views.rejectit,name='rejectit'),
    url(r'^writeremark/(?P<attsheet_id>[0-9]+)',views.writerem,name='remarks'),

    url(r'^logout/',views.log_out,name='log_out'),
]

attendance/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^attendance/',include('att.urls',namespace='att')),
    url(r'^$',include('att.urls',namespace='att')),
]

att/models.py
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator


class attsheet(models.Model):
    name=models.CharField(max_length=30)
    contact_no=models.CharField(max_length=10)
    room_no=models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(25)])
    from_date=models.DateField()
    to_date=models.DateField()
    purpose=models.TextField(max_length=500)
    approved=models.BooleanField(default=False)
    rejected=models.BooleanField(default=False)
    remarks=models.TextField(max_length=100,default="None")

    def __str__(self):
        return self.name+"'s"+' leave entry'

att/forms.py
from django import forms

from .models import attsheet

class attform(forms.ModelForm):
    from_date=forms.DateField(widget=forms.SelectDateWidget)
    to_date = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model=attsheet
        fields=['name','contact_no','room_no','from_date','to_date','purpose']



class approvalform(forms.ModelForm):
    class Meta:
        model=attsheet
        fields=['approved']




att/views.py
from django.shortcuts import render,redirect
from .forms import attform
from django.contrib.auth import authenticate,login,logout
from .models import attsheet

#Create Attendance
def attendancereg(request):
    attsheetform=attform(request.POST)
    s_message="Success! Your response has been recorded!"
    e_message="Please fill all the fields properly!"
    if attsheetform.is_valid():

        attsheetform.save()
        context={
            'success_message': s_message,

        }
        return render(request,'success.html',context)

    else:
        context={
        'attform':attsheetform,
        'error_message':e_message
    }
        return render(request,'error.html',context)

#Login 
def ulogin(request):
    if request.method=='POST':
        username=request.POST.get('username',None)
        password=request.POST.get('password',None)
        guest=authenticate(username=username,password=password)

        if guest is not None:
            if guest.is_active:
                login(request,guest)
                return redirect('att:attviewauth')

    return render(request,'login.html')



def index(request):
    return render(request,'index.html')




#View All The Attendance entries
def attview(request):
    context={
        'all_entries':attsheet.objects.all(),

    }
    return render(request,'all.html',context)


def attviewauth(request):
    if request.user.is_authenticated():
        context = {
        'all_entries': attsheet.objects.all(),

        }
        return render(request, 'auth.html', context)

    return redirect('att:auth_login')

#approval view

def approveit(request,attsheet_id):
    currentsheet = attsheet.objects.get(pk=attsheet_id)
    currentsheet.approved=True

    currentsheet.save()
    msg=" approved successfully!"
    context = {
        'all_entries': attsheet.objects.all(),
        'success_message':msg,
        'sheet':currentsheet,
        'approvance':True,
    }
    return render(request,'auth.html',context)

def rejectit(request,attsheet_id):
    currentsheet = attsheet.objects.get(pk=attsheet_id)
    currentsheet.rejected=True

    currentsheet.save()
    msg=" rejected!"
    context = {
        'all_entries': attsheet.objects.all(),
        'success_message':msg,
        'sheet':currentsheet,
        'rejected':True,
    }
    return render(request,'auth.html',context)


def writerem(request,attsheet_id):
    if request.method=="GET":
        return redirect('att:attviewauth')

    currentsheet = attsheet.objects.get(pk=attsheet_id)

    remark = request.POST.get('remarks', None)
    currentsheet.remarks = remark
    currentsheet.save()
    return redirect('att:attviewauth')


#Log out view
def log_out(request):
    logout(request)
    return redirect('att:index')

templates/all.html
{% extends 'base.html' %}


{% block insert %}
    <div class="container-fluid">
    <div class="jumbotron text-center"><h2>All Leave Entries </h2></div>
    </div>
        <table class="table ">
    <tr>
<th>
   Name
</th>

<th>
Contact Number
</th>


<th>
    Room Number
 </th>

<th>
    From Date
 </th>


<th>
    To Date
 </th>

        <th>Approval Status</th>

        <th>Remarks</th>
    </tr>


   {% for entry in all_entries %}

    <tr {% if entry.approved == True %}class="bg-success"
    {% endif %}
    {% if entry.approved == False and entry.rejected == False %}class="bg-warning"
    {% endif %}
    {% if entry.rejected == True %}class="bg-danger"
    {% endif %}
    >
        <td>
           {{ entry.name }}
        </td>

        <td>
           {{ entry.contact_no }}
        </td>

        <td>
           {{ entry.room_no}}
        </td>

        <td>
           {{ entry.from_date}}
        </td>

        <td>
           {{ entry.to_date }}
        </td>

        <td class="text-center">
            {% if entry.approved == True %}
                <p class="btn btn-success" > <span class="glyphicon glyphicon-ok"></span></p>
            {% endif %}

            {% if entry.rejected == True   %}
                <p class="btn btn-danger"> <span class="glyphicon glyphicon-remove"></span></p>
            {% endif %}

            {% if entry.rejected == False and entry.approved == False %}
                <p class="btn btn-warning"> <span class="glyphicon glyphicon-hourglass"></span></p>
            {% endif %}
        </td>

        <td>
            {% if entry.remarks == "None" and entry.approved == False %}
                <p style="color: #003366;"> No remarks yet!</p>
            {% endif %}
            {%if entry.remarks == "None" and entry.approved == True %}
            <p style="color: #114422;">No remarks</p>
            {% endif %}
        {% if entry.remarks != "None" %}
            {{ entry.remarks }}
        {% endif %}
        </td>

           </tr>
    {% endfor %}

</table>

{% endblock %}

templates/auth.html
{% extends 'base.html' %}


{% block insert %}
    <div class="container-fluid"><div class="well well-sm text-center"><h2>All Leave Entries </h2></div></div>
    <table class="table table-striped">
    <tr>
<th>
   Name
</th>

<th>
Contact Number
</th>


<th>
    Room Number
 </th>

<th>
    From Date
 </th>


<th>
    To Date
 </th>


<th>
    Purpose
 </th>
        <th>
            Remarks
        </th>

        <th>
            Approval Status
        </th>
    </tr>


   {% for entry in all_entries %}
    <tr>
        <td>
           {{ entry.name }}
        </td>

        <td>
           {{ entry.contact_no }}
        </td>

        <td>
           {{ entry.room_no}}
        </td>

        <td>
           {{ entry.from_date}}
        </td>

        <td>
           {{ entry.to_date }}
        </td>

        <td>
           {{ entry.purpose}}
        </td>


        <td>
            {% if entry.remarks == 'None'%}
                <form method="post" action="{% url 'att:remarks' entry.pk %}">
                {% csrf_token %}

                <input type="text" name="remarks">
                    <button class="btn btn-primary" type="submit">Write</button>
                </form>
            {% endif %}
        {% if entry.remarks != 'None' %}
        {{ entry.remarks }}
        {% endif %}
        </td>

        <td>
            {% if entry.approved == True%}
                <button class="btn btn-info" type="button">Approved <span class="glyphicon glyphicon-ok"></span></button>
            {% endif %}

             {% if entry.approved == False and entry.rejected == False%}

               <a href="{% url 'att:approveit' entry.pk %}"><button class="btn btn-success" type="submit" >Approve Now <span class="glyphicon glyphicon-thumbs-up"></span></button></a>
             <a href="{% url 'att:rejectit' entry.pk %}"><button class="btn btn-danger" type="submit">Reject <span class="glyphicon glyphicon-thumbs-down"></span></button></a>
             {% endif %}

        {% if entry.rejected == True%}
            <div style="color:black"><b>Rejected</b></div>
        {% endif %}
        </td>


   </tr>
    {% endfor %}

</table>

<div class="text-center" style="margin-bottom: 10px;">
<button class="btn btn-info" onclick="window.print();">Print</button>
<a class="btn btn-warning" href="{%url 'att:log_out' %}" style="color:white;">Logout</a>
</div>

    {% if approvance == True %}

        <div class="alert alert-success" style="margin-top: 10px; "><strong>Success!</strong> {{ sheet }} {{ success_message }}</div>
    {% endif %}
    {% if rejected == True %}

        <div class="alert alert-danger" style="margin-top: 10px; "><strong>Rejected!</strong> {{ sheet }} {{ success_message }}</div>
    {% endif %}
{% endblock %}

templates/error.html
{% extends 'base.html' %}


{% block insert %}
    <div class="container-fluid">
<div class="text-center well well-lg">
    <h1>Leave Form</h1>
</div>
<div class='alert alert-danger' style="width: fit-content;"><h4>{{ error_message }}</h4></div>
    </div>
    {{ repeat }}

<form method="post" >
{% csrf_token %}
<fieldset class="module aligned ">
{% for field in attform %}
<div class="form-group">
    <span class="small text-centered bg-danger">{{ field.errors }}</span>
    <div class="form-row">
        <div>
    <label>{{ field.label_tag }}</label>
        {{ field }}
    </div>
    </div>
</div>
{% endfor %}
</fieldset>
<div class="container text-center" >
<button class="btn btn-success" type="submit" style="margin-bottom: 10px;">Submit <span class="glyphicon glyphicon-send"></span></button>
</div>
</form>


{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HKS Leave Register</title>
    <!-- Latest compiled and minified CSS -->

 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse" style="margin: 0 auto;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'att:index' %}">Home &nbsp<span class="glyphicon glyphicon-home"></span></a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'att:att' %}">Leave Form &nbsp<span class="glyphicon glyphicon-list"></span></a></li>
      <li><a href="{% url 'att:attview' %}">List of entries &nbsp<span class="glyphicon glyphicon-list-alt"></span></a></li>
      <li><a href="{% url 'att:auth_login' %}">Warden Comitte Login &nbsp<span class="glyphicon glyphicon-tower"></span></a></li>

    </ul>
  </div>
</nav>
<div class="container-fluid text-center jumbotron" style="background-color:#2c3e50;margin: 0 auto;">
    <a href="{% url 'att:att' %}" style="text-decoration: none;" ><h1 style="color:#bCbFb1;">Make an entry <span class="glyphicon glyphicon-pencil"></span></h1></a>

</div>
    <div class="container-fluid text-center jumbotron " style="background-color:#34495e;margin: 0 auto;">
        <a href="{% url 'att:attview' %}" style="text-decoration: none;"><h1 style="color:#bCbFb1;">Check your entry <span class="glyphicon glyphicon-list"></span></h1></a>

</div>

<div class="container-fluid text-center jumbotron" style="background-color:#455a6f;margin: 0 auto;">
        <a href="{% url 'att:auth_login' %}" style="text-decoration: none;" ><h1 style="color:#bCbFb1;">Warden Comittee Login <span class="glyphicon glyphicon-tower"></span></h1></a>

</div>

<div class="container-fluid text-center " style="background-color:#95a5a6;margin: 0 auto; ">
        <h1 style="color:black;">Copyrights &copy
        <div><h6>Reserved <span class="glyphicon glyphicon-sunglasses"></span></h6></div></h1>
      <p>Update release : 1.1</p>

</div>

</body>
</html>


templates/login.html
{% extends 'base.html' %}

{% block insert %}
    <div class="text-center " style="margin-bottom: 200px;">
<form method="post" style="display: inline-block; border: thin double black; border-radius: 5px;">
    {% csrf_token %}
    <fieldset class="module aligned ">

<div class="form-group">
        <div class="form-row">
        <div>
    <label>Username</label>
       <input type="text" name="username">
    </div>
    </div>
</div>


<div class="form-group">
    <div class="form-row">
        <div>
    <label>Password</label>
        <input type="PASSWORD" name="password">
    </div>
    </div>
</div>

</fieldset>
    <button type="submit" class="btn btn-primary" style="margin-bottom: 5px;" >Submit</button>
    </form>
    </div>

{% endblock %}

templates/success.html
{% extends 'base.html' %}


{% block insert %}
    <div class='alert alert-success'><h6><strong>{{ success_message }}</strong></h6></div>
    <div class="text-center container-fluid" style="margin-bottom: 100vh;">
        <a class="btn btn-primary" href="{% url 'att:index' %}" style="color: whitesmoke;">OK</a>
    <br/>
 &nbsp;
    </div>

    {{ present }}

{% endblock %}